apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 5
  replicas: 20
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - name: mydeploy
        image: nginx
        ports:
        - containerPort: 80
