apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 1
  selector:
    color: red
  template:
    metadata:
      name: myrcc
      labels:
        color: red 
    spec:
      containers:
        - name: myc
          image: httpd
          ports:
            - containerPort: 80
